apiVersion: lib.projectsveltos.io/v1beta1
kind: EventTrigger
metadata:
  name: create-touchpoints-trigger
  namespace: projectsveltos
spec:
  sourceClusterSelector:
    matchLabels:
      role: deploy
  eventSourceName: create-touchpoints
  oneForEvent: true
  syncMode: Continuous
  cloudEventAction: '{{if eq .CloudEvent.data.user_role "customer_account_owner"}}Create{{end}}'
  policyRefs:
  - name: create-touchpoints-job
    namespace: projectsveltos
    kind: ConfigMap
