apiVersion: lib.projectsveltos.io/v1beta1
kind: EventTrigger
metadata:
  name: touchpoints-created-trigger
spec:
  sourceClusterSelector:
    matchLabels:
      role: deploy
  eventSourceName: touchpoints-created
  oneForEvent: true
  syncMode: ContinuousWithDriftDetection
  cloudEventAction: Create
  policyRefs:
  - name: touchpoints-created-job
    namespace: default
    kind: ConfigMap

