apiVersion: lib.projectsveltos.io/v1beta1
kind: EventTrigger
metadata:
  name: welcome-email-trigger
  namespace: projectsveltos
spec:
  sourceClusterSelector:
    matchLabels:
      role: deploy
  eventSourceName: welcome-email-sent
  oneForEvent: true
  syncMode: ContinuousWithDriftDetection
  cloudEventAction: Create
  policyRefs:
  - name: welcome-email-job
    namespace: default
    kind: ConfigMap

